dist: trusty

sudo: required

language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get install -yq libusb-dev

before_script:
  - npm run lint
  - npm run build
